### ISSUE TITLE
    vec4 decal_space_pos = view_proj * vec4(FS_IN_WorldPos, 1.0);

### ISSUE THREAD

**Issue by kingofthebongo2008** [diharaw/TextureSpaceDecals#2]
decal has reference to another decal_view_proj and does not compile
should be like this, i guess
vec4 decal_space_pos = view_proj * vec4(FS_IN_WorldPos, 1.0);

**Comment by diharaw** [comment]
Sorry about that. The corrected shaders are commited (I should be the 'light_view_proj' which is actually the 'decal_view_proj'.
